<a href="https://colab.research.google.com/github/RMoulla/DL_Pytorch/blob/main/Tutorial_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fondamentaux Python

## Impression

In [ ]:
print("Bonjour Diego")

Bonjour Diego


In [ ]:
x = 5
print(x)

5


In [ ]:
nom = "Tom"
print(f"Bonjour {nom}")

Bonjour Tom


## Structure conditionnelle

In [ ]:
nom = "Tom"

if nom == "Tom":
    print("Bonjour Tom")
else
    print("Bonjour anonyme")

Bonjour Tom


In [ ]:
nom = "Alice"

if nom == "Tom":
    print("Bonjour Tom")
elif nom == "Alice":
  print("Bonjour Alice")
else:
    print("Bonjour anonyme")

Bonjour Alice


## Listes

In [ ]:
ma_liste = [1, 'Tom', 4, 3.14]
for i in ma_liste:
  print(i)

1
Tom
4
3.14


In [ ]:
list_integ = list(range(10))
list_integ

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
for i in list_integ:
  print(i**2)

0
1
4
9
16
25
36
49
64
81


In [ ]:
# Accéder aux éléments d'une liste
list_integ[0]

0

In [ ]:
# Accéder au dernier élément
list_integ[-3]

7

In [ ]:
# Accéder à plusieurs éléments

list_integ[1:3]

[1, 2]

In [ ]:
# Modifier un élément d'une liste

list_integ[0] = 10
list_integ

[10, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# Ajouter un élément à un liste

list_integ.append(20)
list_integ

[10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 20]

In [ ]:
# Insérer un élément

list_integ.insert(2, 30)
list_integ

[10, 1, 30, 2, 3, 4, 5, 6, 7, 8, 9, 20]

In [ ]:
# Supprimer un élément

del list_integ[2]
list_integ

[10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 20]

In [ ]:
# Supprimer un élément par sa valeur

list_integ.remove(20)
list_integ

[10, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# Etendre une liste

list_integ.extend([40, 50])
list_integ

[10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 40, 50]

In [ ]:
# Identifier l'index d'un élément

list_integ.index(50)

11

In [ ]:
# Trier une liste

list_integ.sort(reverse=True)
list_integ

[50, 40, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [ ]:
# Compréhension de liste

liste_carres = [x**2 for x in list_integ]
liste_carres

[2500, 1600, 100, 81, 64, 49, 36, 25, 16, 9, 4, 1]

In [ ]:
# Copier une liste
list_copy = list_integ.copy()
list_copy

[50, 40, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

## Dictionnaire

In [ ]:
# Créer un dictionnaire from scratch
mon_dict = {"clé1":"valeur1", "clé2":"valeur2", "clé3":"valeur3"}
mon_dict

{'clé1': 'valeur1', 'clé2': 'valeur2', 'clé3': 'valeur3'}

In [ ]:
# Créer un dictionnaire à partir de deux listes

nom = ['Alice', 'Tom', 'Bob']
age = [25, 30, 35]

mon_dict = dict(zip(nom, age))
mon_dict

{'Alice': 25, 'Tom': 30, 'Bob': 35}

In [ ]:
# Accéder à des valeurs avec des clés

mon_dict['Alice']

25

In [ ]:
mon_dict['Alice'] = 40
mon_dict

{'Alice': 40, 'Tom': 30, 'Bob': 35}

In [ ]:
# Supprimer un élément du dictionnaire

del mon_dict['Bob']
mon_dict

{'Alice': 40, 'Tom': 30}

In [ ]:
# Accéder à toutes les clés
mon_dict.keys()

dict_keys(['Alice', 'Tom'])

In [ ]:
# Accéder aux valeurs
mon_dict.values()

dict_values([40, 30])

In [ ]:
# Accéder aux items

mon_dict.items()

dict_items([('Alice', 40), ('Tom', 30)])

In [ ]:
# Copier un dictionnaire

mon_dict_copy = mon_dict.copy()
mon_dict_copy

{'Alice': 40, 'Tom': 30}

## Dataframes

In [ ]:
# Créer un dataframe à partir de listes

import pandas as pd

nom = ['Alice', 'Tom', 'Bob']
age = [25, 30, 35]
ville = ['Paris', 'Lyon', 'Marseille']

df = pd.DataFrame({'Nom': nom, 'Age': age, 'Ville': ville})
df

Nom  Age      Ville
0  Alice   25      Paris
1    Tom   30       Lyon
2    Bob   35  Marseille

In [ ]:
# Accéder à une colonne

df['Age']

0    25
1    30
2    35
Name: Age, dtype: int64

In [ ]:
# Accéder à plusieurs colonnes

df[['Nom', 'Age']]

Nom  Age
0  Alice   25
1    Tom   30
2    Bob   35

In [ ]:
# Accéder à des lignes

df.iloc[1]

Nom       Tom
Age        30
Ville    Lyon
Name: 1, dtype: object

In [ ]:
# Accéder à une ligne par sa valeur

df[df['Nom'] == 'Tom']

Nom  Age Ville
1  Tom   30  Lyon

In [ ]:
# Accéder à une cellule

df.at[1, 'Age']

np.int64(30)

In [ ]:
# Ajouter une colonne

df['Profession'] = ['Ingénieur', 'Boulanger', 'Artiste']
df

Nom  Age      Ville Profession
0  Alice   25      Paris  Ingénieur
1    Tom   30       Lyon  Boulanger
2    Bob   35  Marseille    Artiste

In [ ]:
# Supprimer une colonne

df.drop('Profession', axis=1, inplace=True)
df

Nom  Age      Ville
0  Alice   25      Paris
1    Tom   30       Lyon
2    Bob   35  Marseille

In [ ]:
# Supprimer une ligne

df.drop(1, axis=0, inplace=True)
df

Nom  Age      Ville
0  Alice   25      Paris
2    Bob   35  Marseille

In [ ]:
# Ajouter une ligne avec concat

nouveau_client = pd.DataFrame({'Nom': ['Julie'], 'Age': [28], 'Ville': ['Paris']})
df = pd.concat([df, nouveau_client], ignore_index=True)
df

Nom  Age      Ville
0  Alice   25      Paris
1    Bob   35  Marseille
2    Tom   30       Lyon
3  Julie   28      Paris

In [ ]:
# Merger deux dataframes

df2 = pd.DataFrame({'Nom': ['Alice', 'Tom', 'Bob'], 'Salaire': [50000, 60000, 70000]})
df_merged = pd.merge(df, df2, on='Nom')

df_merged

Nom  Age      Ville  Salaire
0  Alice   25      Paris    50000
1    Bob   35  Marseille    70000
2    Tom   30       Lyon    60000

In [ ]:
# Groupby

df.groupby('Ville').mean('Age')

Age
Ville          
Lyon       30.0
Marseille  35.0
Paris      26.5

In [ ]:
# Sauvegarder un dataframe en csv

df.to_csv('Mon_df.csv', index=False)

#Sauvegarder un dataframe en excel

df.to_excel('Mon_df.xlsx', index=False)

## Calcul numérique avec Numpy



In [ ]:
# Créer un vecteur

import numpy as np

vecteur = np.array([1, 2, 3, 4, 5])
vecteur

array([1, 2, 3, 4, 5])

In [ ]:
# Créer une matrice 3x3

matrice = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrice


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Créer une matrice de zéros

zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Créer une matrice de 1

ones = np.ones((3, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Créer une matrice diagonale de 1

diag = np.eye(3)
diag

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Créer une matrice diagonale [1, 2, 3]

diag = np.diag([1, 2, 3])
diag

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
# Récupérer la diagonale de diag

np.diag(diag)

array([1, 2, 3])

In [ ]:
# Somme de deux matrices

matrice + diag

array([[ 2,  2,  3],
       [ 4,  7,  6],
       [ 7,  8, 12]])

In [ ]:
# produit de deux matrices

matrice.dot(diag)

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [ ]:
# Broadcasting

matrice + [1, 1, 1]

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
# Accéder aux éléments d'une matrice

matrice[0, 0]


np.int64(1)

In [ ]:
# Accéder à une ligne

matrice[0, :]

array([1, 2, 3])

In [ ]:
# Accéder à une colonne

matrice[:, 1]

array([2, 5, 8])

In [ ]:
# La somme des éléments d'une matrice

np.sum(matrice)


np.int64(45)

In [ ]:
# La moyenne des éléments de chaque colonne

np.mean(matrice, axis=0)

array([4., 5., 6.])

In [ ]:
# La dimension de la matrice

matrice.shape

(3, 3)

In [ ]:
# Transformer la matrice en vecteur 1x9

matrice.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Transformer la matrice en vecteur 9x1 avec reshape

matrice.reshape(9, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
# Calculer la transposée d'une matrice
matrice.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Fonctions

In [ ]:
# Fonction de base sans argument
def saluer():
  print("Bonjour")

saluer()

Bonjour


In [ ]:
# Fonction avec un argument

def saluer(nom):
  print(f"Bonjour {nom}")

saluer("Tom")

Bonjour Tom


In [ ]:
# Fonction avec deux arguments

def saluer(nom, age):
  print(f"Bonjour {nom}, tu as {age} ans")

saluer("Tom", 30)

Bonjour Tom, tu as 30 ans


In [ ]:
# Fonction numérique avec deux arguments

def calculer_somme(a, b):
  return a + b

calculer_somme(10, 20)

30

In [ ]:
# fonction qui rajoute 10 à une valeur

def add_ten(number):
    return number + 10

add_ten(15)

25

In [ ]:
# Appliquer la fonction add_ten à la colonne Age

df['Age'] = df['Age'].apply(add_ten)
df

Nom  Age      Ville
0  Alice   35      Paris
1    Bob   45  Marseille
2    Tom   40       Lyon
3  Julie   38      Paris